# netlify.yml
build:
  command: npm run build
  publish: build
plugins:
  - package: netlify-plugin-lighthouse
    settings:
      # Lighthouse 설정
      # 성능 임계값 설정
      performance: 0.8
      accessibility: 0.9
      best-practices: 0.9
      seo: 0.9
